CREATE DATABASE IF NOT EXISTS user_db;
CREATE TABLE IF NOT EXISTS user_db.users(
    id SERIAL PRIMARY KEY,
    username VARCHAR UNIQUE NOT NULL,
    password_hash VARCHAR NOT NULL
);
CREATE EXTENSION pgcrypto;