user-service-config:
  host: "0.0.0.0"
  port: 8080
user-db-config:
  driver: "postgres"
  host: ${USER_DB_HOST}
  port: ${USER_DB_PORT}
  name: user_db
  username: service
  password: ${USER_DB_SERVICE_PASS}
