user-service-config:
  host: "0.0.0.0"
  port: 8080
user-db-config:
  driver: "postgres"
  host: ${USER_DB_HOST}
  port: 5432
  name: ${USER_DB_NAME}
  username: service
  password: ${USER_DB_SERVICE_PASS}