name: golangci-test
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
      - development
      - '**'
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.1
        
        - name: Build
          run: go build -v ./...
          
        - name: Test
          run: go test -v ./...
